-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(from_text_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("priv/from_text_lexer.xrl", 52).


-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("priv/from_text_lexer.erl", 285).
yystate() -> 134.

yystate(135, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(134, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(132, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(130, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(119, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(135, Ics, Line+1, Tlen+1, Action, Alen);
yystate(134, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(134, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,134};
yystate(133, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(133, Ics, Line, Tlen+1, 30, Tlen);
yystate(133, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,133};
yystate(132, [115|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 31, Tlen);
yystate(132, [116|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 31, Tlen);
yystate(132, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,132};
yystate(131, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(130, [119|Ics], Line, Tlen, _, _) ->
    yystate(128, Ics, Line, Tlen+1, 31, Tlen);
yystate(130, [117|Ics], Line, Tlen, _, _) ->
    yystate(122, Ics, Line, Tlen+1, 31, Tlen);
yystate(130, [116|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 31, Tlen);
yystate(130, [115|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 31, Tlen);
yystate(130, [108|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 31, Tlen);
yystate(130, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,130};
yystate(129, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(129, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,129};
yystate(128, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(126, Ics, Line, Tlen+1, Action, Alen);
yystate(128, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,128};
yystate(127, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(126, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Tlen+1, Action, Alen);
yystate(126, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,126};
yystate(125, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Tlen+1, Action, Alen);
yystate(125, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,125};
yystate(124, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(123, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Tlen+1, Action, Alen);
yystate(123, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,123};
yystate(122, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(122, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,122};
yystate(121, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(121, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,121};
yystate(120, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(119, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Tlen+1, Action, Alen);
yystate(119, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(129, Ics, Line, Tlen+1, Action, Alen);
yystate(119, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,119};
yystate(118, [115|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 31, Tlen);
yystate(118, [116|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 31, Tlen);
yystate(118, [111|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 31, Tlen);
yystate(118, [97|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 31, Tlen);
yystate(118, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,118};
yystate(117, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(116, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(116, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,116};
yystate(115, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(115, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,115};
yystate(114, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,114};
yystate(113, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(111, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(110, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(110, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,110};
yystate(109, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(108, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,108};
yystate(107, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(107, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,107};
yystate(106, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(105, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(105, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(104, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,104};
yystate(103, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(102, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,102};
yystate(101, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(101, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,101};
yystate(100, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(100, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,100};
yystate(99, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,99};
yystate(98, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(97, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,96};
yystate(95, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(94, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(94, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,94};
yystate(93, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(92, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(92, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,92};
yystate(91, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,90};
yystate(89, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(88, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,86};
yystate(85, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(83, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,83};
yystate(82, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(81, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(70, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(69, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(61, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(56, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(53, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(42, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(34, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(33, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,33};
yystate(32, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(26, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(25, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(22, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(19, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(15, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(9, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(6, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 20, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,2};
yystate(1, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("priv/from_text_lexer.xrl", 10).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/1}).
-file("priv/from_text_lexer.xrl", 12).
yyaction_1(TokenLine) ->
     { token, { stack, TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("priv/from_text_lexer.xrl", 13).
yyaction_2(TokenLine) ->
     { token, { push, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("priv/from_text_lexer.xrl", 14).
yyaction_3(TokenLine) ->
     { token, { duplicate, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("priv/from_text_lexer.xrl", 15).
yyaction_4(TokenLine) ->
     { token, { copy, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("priv/from_text_lexer.xrl", 16).
yyaction_5(TokenLine) ->
     { token, { swap, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("priv/from_text_lexer.xrl", 17).
yyaction_6(TokenLine) ->
     { token, { discard, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("priv/from_text_lexer.xrl", 18).
yyaction_7(TokenLine) ->
     { token, { slide, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("priv/from_text_lexer.xrl", 20).
yyaction_8(TokenLine) ->
     { token, { arith, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("priv/from_text_lexer.xrl", 21).
yyaction_9(TokenLine) ->
     { token, { add, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("priv/from_text_lexer.xrl", 22).
yyaction_10(TokenLine) ->
     { token, { sub, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("priv/from_text_lexer.xrl", 23).
yyaction_11(TokenLine) ->
     { token, { mul, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("priv/from_text_lexer.xrl", 24).
yyaction_12(TokenLine) ->
     { token, { divide, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("priv/from_text_lexer.xrl", 25).
yyaction_13(TokenLine) ->
     { token, { mod, TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("priv/from_text_lexer.xrl", 27).
yyaction_14(TokenLine) ->
     { token, { heap, TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("priv/from_text_lexer.xrl", 28).
yyaction_15(TokenLine) ->
     { token, { store, TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("priv/from_text_lexer.xrl", 29).
yyaction_16(TokenLine) ->
     { token, { retrieve, TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("priv/from_text_lexer.xrl", 31).
yyaction_17(TokenLine) ->
     { token, { flow, TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("priv/from_text_lexer.xrl", 32).
yyaction_18(TokenLine) ->
     { token, { mark, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("priv/from_text_lexer.xrl", 33).
yyaction_19(TokenLine) ->
     { token, { call, TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("priv/from_text_lexer.xrl", 34).
yyaction_20(TokenLine) ->
     { token, { jump, TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("priv/from_text_lexer.xrl", 35).
yyaction_21(TokenLine) ->
     { token, { jump_zero, TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("priv/from_text_lexer.xrl", 36).
yyaction_22(TokenLine) ->
     { token, { jump_negative, TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("priv/from_text_lexer.xrl", 37).
yyaction_23(TokenLine) ->
     { token, { end_sub, TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("priv/from_text_lexer.xrl", 38).
yyaction_24(TokenLine) ->
     { token, { end_program, TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("priv/from_text_lexer.xrl", 40).
yyaction_25(TokenLine) ->
     { token, { io, TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("priv/from_text_lexer.xrl", 41).
yyaction_26(TokenLine) ->
     { token, { output_char, TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("priv/from_text_lexer.xrl", 42).
yyaction_27(TokenLine) ->
     { token, { output_num, TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("priv/from_text_lexer.xrl", 43).
yyaction_28(TokenLine) ->
     { token, { read_char, TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("priv/from_text_lexer.xrl", 44).
yyaction_29(TokenLine) ->
     { token, { read_num, TokenLine } } .

-compile({inline,yyaction_30/2}).
-file("priv/from_text_lexer.xrl", 46).
yyaction_30(TokenChars, TokenLine) ->
     { token, { number, TokenLine, TokenChars } } .

-compile({inline,yyaction_31/2}).
-file("priv/from_text_lexer.xrl", 47).
yyaction_31(TokenChars, TokenLine) ->
     { token, { label, TokenLine, TokenChars } } .

-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 290).
